routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('login/facebook', 'Auth\LoginController@redirectToProvider');
Route::get('login/facebook/callback', 'Auth\LoginController@handleProviderCallback');

Route::get('/', 'HomeController@index')->name('home');

Route::middleware(['auth'])->group(function(){

	Route::resource('companies', 'CompaniesController');

	Route::resource('projects', 'ProjectsController');
	Route::post('projects/adduser', 'ProjectsController@adduser')->name('projects.adduser');

	Route::resource('tasks', 'TasksController');
	Route::post('tasks/adduser', 'TasksController@adduser')->name('tasks.adduser');

	// Route::resource('roles', 'RolesController');

	Route::get('getUsers', 'UsersController@getUsers')->name('get.users');
	Route::resource('users', 'UsersController');

	Route::post('comments', 'CommentsController@store')->name('comments.store');

});

app/Project.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Project extends Model
{
    protected $fillable = [
    	'name',
    	'description',
    	'company_id',
    	'user_id',
    	'days'
    ];

    //A project belongs to many users
    public function users()
    {
        return $this->belongsToMany('App\User');
    }

    //A project has one company
    public function company()
    {
        return $this->belongsTo('App\Company');
    }

    public function comments()
    {
        return $this->morphMany('App\Comment', 'commentable');
    }

    public function tasks()
    {
        return $this->hasMany('App\Task');
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/ProjectsController.php
<?php

namespace App\Http\Controllers;

use App\Project;
use App\Company;
// use App\User;
use App\ProjectUser;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Http\Requests\Projects\ProjectsCreateFormRequest;
use App\Http\Requests\Projects\AddMemberFormRequest;
use Illuminate\Support\MessageBag;
use App\Repositories\ProjectRepositories\ProjectRepositoryInterface;

class ProjectsController extends Controller
{
    protected $projects;

    public function __construct(ProjectRepositoryInterface $projects)
    {
        $this->middleware(['permission:create_project'])->only('create');
        $this->middleware(['permission:edit_project'])->only('edit');
        $this->middleware(['permission:delete_project'])->only('delete');
        $this->projects = $projects;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $projects = $this->projects->allProjects();

        // $projects = DB::table('projects')->paginate(10);

        return view('projects.index', ['projects' => $projects]);
    }

    public function adduser(AddMemberFormRequest $request,MessageBag $msg)
    {
        $user = Auth::user();

        // $project = Project::find($request->input('project_id'));
        $project = $this->projects->findProject($request);

        if(!$user->can('addUser', $project))
        {
            $msg->add('member', 'Error adding user to project');
            return redirect()
                ->route('projects.show', ['project' => $project->id])
                ->withErrors($msg);
        }

        // $user = User::where('email', $request->input('email'))->first();
        $user = $this->projects->userEmail($request);

        if ($user && $project)
        {
            $project->users()->attach($user->id);

            return redirect()->route('projects.show', ['project' => $project->id])
                ->with('success', $request->input('email').' was added to the project successfully');
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        $company_id = $request->company_id;
        
        $companies = null;

        $companies = Company::all();

        return view('projects.create', ['company_id' => $company_id, 'companies' => $companies]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ProjectsCreateFormRequest $request)
    {
        $project = $this->projects->addProject($request);

        return redirect()->route('projects.index')
            ->with('success', 'Project added successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\project  $project
     * @return \Illuminate\Http\Response
     */
    public function show(Project $project)
    {
        $comments = $project->comments;

        return view('projects.show', ['project' => $project, 'comments' => $comments]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\project  $project
     * @return \Illuminate\Http\Response
     */
    public function edit(Project $project)
    {
        $user = Auth::user();

        if ($user->can('update', $project)) 
        {
            return view('projects.edit', ['project' => $project]);
        }
        
        return response(view('errors.403'), 403);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\project  $project
     * @return \Illuminate\Http\Response
     */
    public function update(ProjectsCreateFormRequest $request, Project $project)
    {
        $user = Auth::user();

        if ($user->can('update', $project)) 
        {
            $this->projects->updateProject($request, $project);   

            return redirect()->route('projects.show',['project' => $project->id])
                ->with('success', 'Project updated successfully');
        }

        return response(view('errors.403'), 403);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\project  $project
     * @return \Illuminate\Http\Response
     */
    public function destroy(Project $project)
    {
        $user = Auth::user();

        if ($user->can('update', $project))
        {
            $project->delete();
            
            return redirect()->route('projects.index')
                ->with('success', 'Project deleted successfully');
        }

        return response(view('errors.403'), 403);
    }
}

resources/views/projects/create.blade.php
@extends('layouts.app')
@section('content')

  <div class="col-md-9 col-lg-9 col-sm-9 pull-left">

    <h1>Create a new Project</h1>
    <div class="row col-md-12 col-lg-12 col-sm-12" style=" background: white; padding-top: 10px; border:solid 1px #e3e3e3; border-radius: 10px;">

      <form method="post" action="{{ route('projects.store') }}">
        {{ csrf_field() }}

        <div class="form-group @if($errors->has('name')) has-error @endif">
          <label for="project-name">Name <span class="required">*</span></label>
          <input  placeholder="Enter name"
                  id="project-name"
                  name="name"
                  spellcheck="false"
                  class="form-control" />
        </div>

        <div class="form-group">
          <label for="company-content">Select Company</label>

          <select name="company_id" class="form-control">
              @foreach($companies as $company)
                <option @if($company_id == $company->id) selected="selected" @endif value="{{ $company->id }}">{{ $company->name }}</option>
              @endforeach

          </select>
        </div>

        <div class="form-group @if($errors->has('name')) has-error @endif">
          <label for="project-days">Time frame (days) <span class="required">*</span></label>
          <input  type="number"
                  placeholder="Enter number of days"
                  id="project-says"
                  name="days"
                  class="form-control" />
        </div>

        <div class="form-group">
          <label for="project-content">Description</label>
          <textarea placeholder="Enter description"
                    style="resize: vertical;" 
                    id="project-content"
                    name="description"
                    rows="5" spellcheck="false" 
                    class="form-control autosize-target text-left">
          </textarea>
        </div>

        <div class="form-group">
            <input type="submit" class="btn btn-primary" value="Submit"/>
        </div>

      </form>
    </div>
  </div>

  <div class="col-sm-3 col-md-3 col-lg-3 ">
    <div class="sidebar-module">
      <h4>Actions</h4>
      <ol class="list-unstyled">
        <li><a href="{{ route('projects.index') }} ">All projects</a></li>
      </ol>
    </div>
  </div>
@endsection

resources/views/projects/edit.blade.php
@extends('layouts.app')
@section('content')

  <div class="col-md-9 col-lg-9 col-sm-9 pull-left">

    <h1>Update Project</h1>
    <div class="row col-md-12 col-lg-12 col-sm-12" style=" background: white; padding-top: 10px; border:solid 1px #e3e3e3; border-radius: 10px;">

      <form method="post" action="{{ route('projects.update',[$project->id]) }}">
        {{ csrf_field() }}

        <input type="hidden" name="_method" value="put">

        <div class="form-group @if($errors->has('name')) has-error @endif">
          <label for="project-name">Name <span class="required">*</span></label>
          <input  placeholder="Enter name"
                  id="project-name"
                  name="name"
                  spellcheck="false"
                  class="form-control"
                  value="{{ $project->name }}" />
        </div>

        <div class="form-group @if($errors->has('days')) has-error @endif">
          <label for="project-days">Time frame (days) <span class="required">*</span></label>
            <input  type="number" 
                    placeholder="Enter number of days"
                    id="project-days"
                    name="days"
                    class="form-control"
                    value="{{ $project->days }}" />
        </div>

        <div class="form-group">
          <label for="project-content">Description</label>
          <textarea placeholder="Enter description"
                  style="resize: vertical;" 
                  id="project-content"
                  name="description"
                  rows="5" spellcheck="false" 
                  class="form-control autosize-target text-left">{{ $project->description }}
          </textarea>
        </div>

        <div class="form-group">
            <input type="submit" class="btn btn-primary" value="Submit"/>
        </div>

      </form>
    </div>
  </div>

  <div class="col-sm-3 col-md-3 col-lg-3 ">
    <div class="sidebar-module">
      <h4>Actions</h4>
      <ol class="list-unstyled">
        <li><a href="{{ route('projects.show', $project->id) }} ">View project</a></li>
        <li><a href="{{ route('projects.index') }} ">All projects</a></li>
      </ol>
    </div>
  </div>
@endsection

resources/views/projects/index.blade.php
@extends('layouts.app')
@section('content')

<div class="col-md-6 col-lg-6 col-md-offset-3 col-lg-offset-3">
  <div class="panel panel-primary">
    <div class="panel-heading">Projects
      @if(auth()->user()->can('create_project') || auth()->user()->hasRole('admin')) 
        <a href="{{ route('projects.create') }}" style="color: white; float: right;">Create new project</a>
      @endif
    </div>
    <div class="panel-body">
      <ul class="list-group">
        @foreach($projects as $project)
          <li class="list-group-item">
            <a href="{{ route('projects.show', $project->id) }}"> {{ $project->name }} </a>
            @if(Auth::user()->id == $project->user_id)
              <a class="pull-right" href="{{ route('projects.show', $project->id) }}"> Manage </a>
            @endif
          </li>
        @endforeach
      </ul>
    </div>
  </div>
  <div class="pull-right">{{ $projects->links() }}</div>
</div>
@endsection

resources/views/projects/show.blade.php
@extends('layouts.app')
@section('content')

  <div class="col-md-9 col-lg-9 col-sm-9 pull-left">
    
    <div class="well well-lg">
      <div class="container">
        <h1 class="display-3">{{ $project->name }}</h1>
        <p>Created by: <strong><a href="users/{{$project->user->id}}">{{ $project->user->name }}</a></strong></p>
        <p>Project for: <strong><a href="{{ route('companies.show', $project->company->id) }}">{{ $project->company->name }}</a> </strong></p>
        <p>Description: <strong> {{ $project->description }} </strong></p>
        <p>Created at: <strong> {{ $project->created_at }} </strong></p>
        <p>Time frame: <strong> {{ $project->days }} days </strong></p>
      </div>
    </div>

    <div class="container">
      <div class="row col-md-9 col-lg-9 col-sm-9 pull-left" 
           style=" background: white; padding-bottom: 5px; margin-bottom: 20px; border:solid 1px #e3e3e3; border-radius: 10px;">

        @foreach($project->tasks as $task)
          <div class="col-md-4">
            <h2>{{ $task->name }}</h2>
            <p>Timeframe: {{ $task->days }} days</p>
            <p><a class="btn btn-primary" href="{{ route('tasks.show', $task->id) }}" role="button">View Task &raquo;</a></p>
          </div>
        @endforeach

      </div>
      
      @include('partials.comments')

      <div class="row col-md-9 col-lg-9 col-sm-9 pull-left" style="
      background: white; margin-top: 20px; margin-bottom: 20px; border:solid 1px #e3e3e3; border-radius: 10px;">

        <div class="row container-fluid">
           <form method="post" action="{{ route('comments.store') }}">
            
            {{ csrf_field() }}

            <input type="hidden" name="commentable_type" value="App\Project">
            <input type="hidden" name="commentable_id" value="{{ $project->id }}">
            <h2>Add a comment</h2>
            <div class="form-group @if($errors->has('url')) has-error @endif">
              <label for="comment-content">Work done (url/title)</label>
              <textarea placeholder="Enter url/title"
                      style="resize: vertical;" 
                      id="comment-content"
                      name="url"
                      rows="2" spellcheck="false" 
                      class="form-control autosize-target text-left"></textarea>
            </div>

            <div class="form-group @if($errors->has('body')) has-error @endif">
              <label for="comment-content">Comment</label>
              <textarea placeholder="Enter comment"
                      style="resize: vertical;" 
                      id="comment-content"
                      name="body"
                      rows="3" spellcheck="false" 
                      class="form-control autosize-target text-left"></textarea>
            </div>

            <div class="form-group">
                <input type="submit" class="btn btn-primary" value="Submit"/>
            </div>

          </form>
        </div>
      </div>
    </div> <!-- /container -->
  </div>

  <div class="col-sm-3 col-md-3 col-lg-3 ">
       
    <div class="sidebar-module">
      <h4>Actions</h4>
      <ol class="list-unstyled">
        @if(Auth::user()->id == $project->user->id || auth()->user()->hasRole('admin'))
          <li><a href="{{ route('projects.edit', $project->id) }}"><i class="fas fa-edit"></i> Edit</a></li>
        @endif
        @if(Auth::user()->id == $project->user->id || auth()->user()->can('create_task'))
          <li><a href="{{ route('tasks.create', ['project_id' => $project->id]) }}"><i class="fas fa-plus-circle"></i> Add Task</a></li>
        @endif
        <li><a href="{{ route('projects.index') }}"><i class="fas fa-list-ul"></i> List of projects</a></li>

        @if(Auth::user()->id == $project->user->id || auth()->user()->hasRole('admin'))
          <li>
            <a href=""
              onclick="var result = confirm('Are you sure you want to delete this Project?');
                if (result) 
                {
                    event.preventDefault();
                    document.getElementById('delete-form').submit();
                }
            ">
              <i class="fas fa-trash-alt"></i> Delete
            </a>

            <form id="delete-form" action="{{ route('projects.destroy',[$project->id]) }}"
              method="POST" style="display: none;">
                <input type="hidden" name="_method" value="delete">
                {{ csrf_field() }}
            </form>

          </li>
        @endif
      </ol>
      <hr/>

      @if(Auth::user()->id == $project->user->id)
        <h4>Add a member</h4>
        <div class="row">
          <div class="col-lg-12 col-md-12 col-sm-12">
            <form id="add-user" action="{{ route('projects.adduser') }}" method="POST">
              {{ csrf_field() }}
              <div class="input-group">
                <input class="form-control" name="project_id" value="{{ $project->id }}" type="hidden">
                <input type="text" class="form-control" name="email" placeholder="Email">
                <span class="input-group-btn">
                  <button class="btn btn-default" type="submit">Add!</button>
                </span>
              </div><!-- /input-group -->
            </form>
          </div><!-- /.col-lg-6 -->
        </div><!-- /.row -->
        <hr/>
      @endif

      <h4>Members</h4>
      <ol class="list-unstyled">
        @foreach($project->users as $user)
          <li><a href="#"> {{ $user->email }} </a></li>
        @endforeach
      </ol>

    </div>          
  </div>
@endsection