routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('login/facebook', 'Auth\LoginController@redirectToProvider');
Route::get('login/facebook/callback', 'Auth\LoginController@handleProviderCallback');

Route::get('/', 'HomeController@index')->name('home');

Route::middleware(['auth'])->group(function(){

	Route::resource('companies', 'CompaniesController');

	Route::resource('projects', 'ProjectsController');
	Route::post('projects/adduser', 'ProjectsController@adduser')->name('projects.adduser');

	Route::resource('tasks', 'TasksController');
	Route::post('tasks/adduser', 'TasksController@adduser')->name('tasks.adduser');

	// Route::resource('roles', 'RolesController');

	Route::get('getUsers', 'UsersController@getUsers')->name('get.users');
	Route::resource('users', 'UsersController');

	Route::post('comments', 'CommentsController@store')->name('comments.store');

});

app/Company.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Company extends Model
{
     protected $fillable = [
    	'name',
    	'description',
    	'user_id'
    ];

    protected $id = 'id';

     //A company has one user
    public function user()
    {
        return $this->belongsTo('App\User');
    }

    public function projects()
    {
        return $this->hasMany('App\Project');
    }

    public function comments()
    {
        return $this->morphMany('App\Comment', 'commentable');
    }
}

app/Http/Controllers/CompaniesController.php
<?php

namespace App\Http\Controllers;

use App\Company;
// use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;
use App\Http\Requests\Companies\CompaniesCreateFormRequest;
use App\Repositories\CompanyRepositories\CompanyRepositoryInterface;

class CompaniesController extends Controller
{
    protected $companies;

    public function __construct(CompanyRepositoryInterface $companies)
    {
        $this->middleware(['permission:create_company'])->only('create');
        $this->middleware(['permission:edit_company'])->only('edit');
        $this->middleware(['permission:delete_company'])->only('delete');
        $this->companies = $companies;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $companies = $this->companies->allCompanies();

        return view('companies.index', ['companies' => $companies]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('companies.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CompaniesCreateFormRequest $request)
    {
        $company = $this->companies->addCompany($request);
        return redirect()->route('companies.index')->with('success', 'Company added successfully');

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Company  $company
     * @return \Illuminate\Http\Response
     */
    public function show(Company $company)
    {
        $comments = $company->comments;

        return view('companies.show', ['company' => $company, 'comments' => $comments]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Company  $company
     * @return \Illuminate\Http\Response
     */
    public function edit(Company $company)
    {
        $user = Auth::user();

        if ($user->can('update', $company))
        {
            return view('companies.edit', ['company' => $company]);
        }

        return response(view('errors.403'), 403);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Company  $company
     * @return \Illuminate\Http\Response
     */
    public function update(CompaniesCreateFormRequest $request, Company $company)
    {
        $user = Auth::user();

        if ($user->can('update', $company))
        {
            $this->companies->updateCompany($request, $company);

            return redirect()->route('companies.show',['company' => $company->id])
                    ->with('success', 'Company updated successfully');
        }

        return response(view('errors.403'), 403);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Company  $company
     * @return \Illuminate\Http\Response
     */
    public function destroy(Company $company)
    {
        dd($company);
        $user = Auth::user();

        if ($user->can('delete', $company))
        {
            $company->delete();

            return redirect()->route('companies.index')
                ->with('success', 'Company deleted successfully');
        }

        return response(view('errors.403'), 403);
    }
}

resources/views/companies/create.blade.php
@extends('layouts.app')
@section('content')

  <div class="col-md-9 col-lg-9 col-sm-9 pull-left">
    <h1>Create a new Company</h1>
    <div class="row col-md-12 col-lg-12 col-sm-12" style=" background: white; padding-top: 10px; border:solid 1px #e3e3e3; border-radius: 10px;">
      <form method="post" action="{{ route('companies.store') }}" >
        {{ csrf_field() }}

        <div class="form-group @if($errors->has('name')) has-error @endif">
          <label for="company-name">Name <span class="required">*</span></label>
          <input  placeholder="Enter name"
                  id="company-name"
                  name="name"
                  spellcheck="false"
                  class="form-control" />
        </div>

        <div class="form-group"> 
          <label for="company-content">Description</label>
          <textarea placeholder="Enter description"
                  style="resize: vertical;" 
                  id="company-content"
                  name="description"
                  rows="5" spellcheck="false" 
                  class="form-control autosize-target text-left">
          </textarea>
        </div>

        <div class="form-group">
            <input type="submit" class="btn btn-primary" value="Submit"/>
        </div>

      </form>
    </div>
  </div>

  <div class="col-sm-3 col-md-3 col-lg-3 ">
    <div class="sidebar-module">
      <h4>Actions</h4>
      <ol class="list-unstyled">
        <li><a href="{{route('companies.index')}}">All companies</a></li>
      </ol>
    </div>
  </div>
@endsection

resources/views/companies/edit.blade.php
@extends('layouts.app')
@section('content')

  <div class="col-md-9 col-lg-9 col-sm-9 pull-left">
    <h1>Update Company</h1>
    <div class="row col-md-12 col-lg-12 col-sm-12" style=" background: white; padding-top: 10px; border:solid 1px #e3e3e3; border-radius: 10px;">
      <form method="post" action="{{ route('companies.update', $company->id) }}">
        {{ csrf_field() }}

        <input type="hidden" name="_method" value="put">

        <div class="form-group @if($errors->has('name')) has-error @endif">
          <label for="company-name">Name <span class="required">*</span></label>
          <input  placeholder="Enter name"
                  id="company-name"
                  name="name"
                  spellcheck="false"
                  class="form-control"
                  value="{{ $company->name }}" />
        </div>

        <div class="form-group">
          <label for="company-content">Description</label>
          <textarea placeholder="Enter description"
                  style="resize: vertical;" 
                  id="company-content"
                  name="description"
                  rows="5" spellcheck="false" 
                  class="form-control autosize-target text-left">{{ $company->description }}</textarea>
        </div>

        <div class="form-group">
            <input type="submit" class="btn btn-primary" value="Submit"/>
        </div>

      </form>
    </div>
  </div>

  <div class="col-sm-3 col-md-3 col-lg-3 ">
    <div class="sidebar-module">
      <h4>Actions</h4>
      <ol class="list-unstyled">
        <li><a href="{{ route('companies.show', $company->id) }} ">View company</a></li>
        <li><a href="{{ route('companies.index') }}">All companies</a></li>
      </ol>
    </div>
  </div>
@endsection

resources/views/companies/index.blade.php
@extends('layouts.app')
@section('content')
  @if(flash()->message)
      <div class="{{ flash()->class }}">
          {{ flash()->message }}
      </div>
  @endif
  <div class="col-md-6 col-lg-6 col-md-offset-3 col-lg-offset-3">
    <div class="panel panel-primary">

      <div class="panel-heading">Companies
        @if(auth()->user()->can('create_company') || auth()->user()->hasRole('admin'))
          <a href="{{ route('companies.create') }}" style="color: white; float: right;">Create a new company</a>
        @endif
      </div>

      <div class="panel-body">
        <ul class="list-group">
          @foreach($companies as $company)
            <li class="list-group-item">
              <a href="{{ route('companies.show', $company->id) }}"> {{ $company->name }} </a>
              @if(Auth::user()->id == $company->user_id)
                <a class="pull-right" href="{{ route('companies.show', $company->id) }}"> Manage </a>
              @endif
            </li>
          @endforeach
        </ul>
      </div>
    </div>
    <div class="pull-right">{{ $companies->links() }}</div>
  </div>
@endsection

resources/views/companies/show.blade.php
@extends('layouts.app')
@section('content')
<?php $errors = Session::has('errors') ? Session::get('errors') : $errors; ?>
  <div class="col-md-9 col-lg-9 col-sm-9 pull-left">

    <div class="jumbotron">
      <div class="container">
        <h1 class="display-3">{{$company->name}}</h1>
        <p>Created by: <strong><a href="users/{{$company->user->id}}">{{ $company->user->name }}</a></strong></p>
        <p>Description: <strong> {{ $company->description }} </strong></p>
      </div>
    </div>

    <div class="container">

      <div class="row col-md-9 col-lg-9 col-sm-9 pull-left"
        style="background: white; margin-bottom: 20px; border:solid 1px #e3e3e3; border-radius: 10px;">

        <h2><i class="fas fa-paperclip"></i> Projects</h2>
        @foreach($company->projects as $project)
          <div class="col-md-4">
            <h2>{{ $project->name }}</h2>
            <p>{{ $project->description }}</p>
            <p><a class="btn btn-primary" href="{{ route('projects.show', $project->id) }}" role="button">View Project &raquo;</a></p>
          </div>
        @endforeach
      </div>

      @include('partials.comments')

      <div class="row col-md-9 col-lg-9 col-sm-9 pull-left"
      style="background: white; margin-top: 20px; margin-bottom: 20px; border:solid 1px #e3e3e3; border-radius: 10px;">

        <div class="row container-fluid">
          <form method="post" action="{{ route('comments.store') }}" enctype='multipart/form-data'>
            {{ csrf_field() }}

            <input type="hidden" name="commentable_type" value="App\Company">
            <input type="hidden" name="commentable_id" value="{{ $company->id }}">

            <h2><i class="far fa-plus-square"></i> Add a comment</h2>
            <div class="form-group @if($errors->has('url')) has-error @endif">
              <label for="comment-content">Work done (url/title)</label>
              <textarea placeholder="Enter url/title"
                      style="resize: vertical;"
                      id="comment-content"
                      name="url"
                      rows="2"
                      spellcheck="false"
                      class="form-control autosize-target text-left">
              </textarea>
            </div>

            <div class="form-group @if($errors->has('body')) has-error @endif">
              <label for="comment-content">Comment</label>
              <textarea placeholder="Enter comment"
                      style="resize: vertical;"
                      id="comment-content"
                      name="body"
                      rows="3"
                      spellcheck="false"
                      class="form-control autosize-target text-left">
              </textarea>
            </div>

            <div class="form-group">
                <input type="submit" class="btn btn-primary" value="Submit"/>
            </div>
          </form>
        </div>
      </div>
    </div> <!-- /container -->
  </div>

  <div class="col-sm-3 col-md-3 col-lg-3 ">

    <div class="sidebar-module">
      <h4>Actions</h4>
      <ol class="list-unstyled">
        @if(Auth::user()->id == $company->user->id || auth()->user()->can('edit_company'))
          <li><a href="{{ route('companies.edit', $company->id) }}"><i class="fas fa-edit"></i> Edit</a></li>
        @endif
        @if(Auth::user()->id == $company->user->id || auth()->user()->can('create_project'))
          <li><a href="{{ route('projects.create', ['company_id' => $company->id]) }}"><i class="fas fa-plus-circle"></i> Add Project</a></li>
        @endif
          <li><a href="{{ route('companies.index') }}"><i class="fas fa-list-ul"></i> List of Companies</a></li>

        @if(Auth::user()->id == $company->user->id || auth()->user()->can('delete_company'))
          <li>

            <a href=""
              onclick="var result = confirm('Are you sure you want to delete this Project?');
                if (result) {
                    event.preventDefault();
                    document.getElementById('delete-form').submit();
                }
            ">
              <i class="fas fa-trash-alt"></i> Delete
            </a>

            <form id="delete-form" action="{{ route('companies.destroy', $company->id) }}"
              method="POST" style="display: none;">
                {{ method_field('DELETE') }}
                {{ csrf_field() }}
            </form>
          </li>
        @endif
      </ol>
    </div>
  </div>
@endsection