routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('login/facebook', 'Auth\LoginController@redirectToProvider');
Route::get('login/facebook/callback', 'Auth\LoginController@handleProviderCallback');

Route::get('/', 'HomeController@index')->name('home');

Route::middleware(['auth'])->group(function(){

	Route::resource('companies', 'CompaniesController');

	Route::resource('projects', 'ProjectsController');
	Route::post('projects/adduser', 'ProjectsController@adduser')->name('projects.adduser');

	Route::resource('tasks', 'TasksController');
	Route::post('tasks/adduser', 'TasksController@adduser')->name('tasks.adduser');

	// Route::resource('roles', 'RolesController');

	Route::get('getUsers', 'UsersController@getUsers')->name('get.users');
	Route::resource('users', 'UsersController');

	Route::post('comments', 'CommentsController@store')->name('comments.store');

});

app/Task.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
     protected $fillable = [
    	'name',
    	'project_id',
    	'user_id',
    	'company_id',
    	'days',
    	'hours'
    ];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    //A task has one project
    public function project()
    {
        return $this->belongsTo('App\Project');
    }

    //A task has one company
    public function company()
    {
        return $this->belongsTo('App\Company');
    }

     //A task belongs to many users
    public function users()
    {
    	return $this->belongsToMany('App\User');
    }

    public function comments()
    {
        return $this->morphMany('App\Comment', 'commentable');
    }
}

app/Http/Controllers/TasksController.php
<?php

namespace App\Http\Controllers;

use App\Task;
use App\Project;
// use App\User;
use App\TaskUser;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Http\Requests\Tasks\TasksCreateFormRequest;
use App\Http\Requests\Tasks\AddMemberFormRequest;
use Illuminate\Support\MessageBag;
use App\Repositories\TaskRepositories\TaskRepositoryInterface;

class TasksController extends Controller
{
    protected $tasks;

    public function __construct(TaskRepositoryInterface $tasks)
    {
        $this->middleware(['permission:create_task'])->only('create');
        $this->middleware(['permission:edit_task'])->only('edit');
        $this->middleware(['permission:delete_task'])->only('delete');
        $this->tasks = $tasks;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $tasks = $this->tasks->allTasks();
        // $tasks = DB::table('tasks')->paginate(10);

        return view('tasks.index', ['tasks' => $tasks]);
    }

    public function addUser(AddMemberFormRequest $request, MessageBag $msg)
    {
        $user = Auth::user();
        //add user to task
        $task = $this->tasks->findTask($request);

        if(!$user->can('addUser', $task))
        {
            $msg->add('member', 'Error adding user to task');
            return redirect()
                ->route('tasks.show', ['task' => $task->id])
                ->withErrors($msg);
        }

        $user = $this->tasks->userEmail($request);

        if ($user && $task)
        {
            $task->users()->attach($user->id);

            return redirect()->route('tasks.show', ['task' => $task->id])
                    ->with('success', $request->input('email').' was added to the task successfully');
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        $project_id = $request->project_id;

        $projects = null;

        $projects = Project::all();
        
        return view('tasks.create', ['project_id' => $project_id, 'projects' => $projects]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(TasksCreateFormRequest $request)
    {
        $task = $this->tasks->addTask($request);

        if ($task)
        {
            return redirect()->route('tasks.index')
                     ->with('success', 'Task added successfully');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\task  $task
     * @return \Illuminate\Http\Response
     */
    public function show(Task $task)
    {
        $comments = $task->comments;

        return view('tasks.show', ['task' => $task, 'comments' => $comments]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\task  $task
     * @return \Illuminate\Http\Response
     */
    public function edit(Task $task)
    {
        $user = Auth::user();

        if ($user->can('update', $task)) 
        {
            return view('tasks.edit', ['task' => $task]);
        }

        return response(view('errors.403'), 403);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\task  $task
     * @return \Illuminate\Http\Response
     */
    public function update(TasksCreateFormRequest $request, Task $task)
    {
        $user = Auth::user();

        if ($user->can('update', $task)) 
        {
            $this->tasks->updateTask($request, $task);

            if ($task)
            {
                return redirect()->route('tasks.show',['task' => $task->id])
                        ->with('success', 'Task updated successfully');
            }
        }

        return response(view('errors.403'), 403);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\task  $task
     * @return \Illuminate\Http\Response
     */
    public function destroy(Task $task)
    {
        $user = Auth::user();

        if ($user->can('delete', $task)) 
        {
            $task->delete();
            
            return redirect()->route('tasks.index')
                    ->with('success', 'Task deleted successfully');
        }

        return response(view('errors.403'), 403);
    }
}

resources/views/tasks/create.blade.php
@extends('layouts.app')
@section('content')

  <div class="col-md-9 col-lg-9 col-sm-9 pull-left">

    <h1>Create a new task</h1>
    <div class="row col-md-12 col-lg-12 col-sm-12" style=" background: white; padding-top: 10px; border:solid 1px #e3e3e3; border-radius: 10px;">
       
      <form method="post" action="{{ route('tasks.store') }}">
        {{ csrf_field() }}

        <input name="project_id" type="hidden" value="{{ $project_id }}" />
        
        <div class="form-group @if($errors->has('name')) has-error @endif">
          <label for="task-name">Name <span class="required">*</span></label>
          <input  placeholder="Enter name"
                  id="task-name"
                  name="name"
                  spellcheck="false"
                  class="form-control" />
        </div>

        <div class="form-group">
          <label for="project-content">Select project</label>

          <select name="project_id" class="form-control">

            @foreach($projects as $project)
              <option @if($project_id == $project->id) selected="selected" @endif value="{{ $project->id }}">{{ $project->name }}</option>
            @endforeach

          </select>
        </div>

        <div class="form-group @if($errors->has('days')) has-error @endif">
          <label for="task-days">Time frame (days) <span class="required">*</span></label>
            <input  type="number" 
                    placeholder="Enter number of days"
                    id="task-days"
                    name="days"
                    class="form-control" />
        </div>

        <div class="form-group">
            <input type="submit" class="btn btn-primary" value="Submit"/>
        </div>
        
      </form>
    </div>
  </div>

  <div class="col-sm-3 col-md-3 col-lg-3 ">
    <div class="sidebar-module">
      <h4>Actions</h4>
      <ol class="list-unstyled">
        <li><a href="{{ route('tasks.index') }}">All tasks</a></li>
      </ol>
    </div>
  </div>
@endsection

resources/views/tasks/edit.blade.php
@extends('layouts.app')
@section('content')

  <div class="col-md-9 col-lg-9 col-sm-9 pull-left">

    <h1>Update Task</h1>
    <div class="row col-md-12 col-lg-12 col-sm-12" style=" background: white; padding-top: 10px; border:solid 1px #e3e3e3; border-radius: 10px;">
       
      <form method="post" action="{{ route('tasks.update',[$task->id]) }}">
        {{ csrf_field() }}

        <input type="hidden" name="_method" value="put">

        <div class="form-group @if($errors->has('name')) has-error @endif">
          <label for="task-name">Name <span class="required">*</span></label>
          <input  placeholder="Enter name"
                  id="task-name"
                  name="name"
                  spellcheck="false"
                  class="form-control"
                  value="{{ $task->name }}" />
        </div>

        <div class="form-group @if($errors->has('name')) has-error @endif">
          <label for="task-days">Time frame (days) <span class="required">*</span></label>
            <input  type="number" 
                    placeholder="Enter number of days"
                    id="task-says"
                    name="days"
                    class="form-control"
                    value="{{ $task->days }}" />
        </div>

        <div class="form-group">
            <input type="submit" class="btn btn-primary" value="Submit"/>
        </div>
        
      </form>
    </div>
  </div>

  <div class="col-sm-3 col-md-3 col-lg-3 ">
    <div class="sidebar-module">
      <h4>Actions</h4>
      <ol class="list-unstyled">
        <li><a href="{{ route('tasks.show', $task->id) }}">View task</a></li>
        <li><a href="{{ route('tasks.index') }}">All tasks</a></li>
      </ol>
    </div>
  </div>
@endsection

resources/views/tasks/index.blade.php
@extends('layouts.app')
@section('content')

<div class="col-md-6 col-lg-6 col-md-offset-3 col-lg-offset-3">
  <div class="panel panel-primary">
    
    <div class="panel-heading">Tasks 
      @if(auth()->user()->can('create_task') || auth()->user()->hasRole('admin')) 
        <a href="{{ route('tasks.create') }}" style="color: white; float: right;">Create new task</a>
      @endif
    </div>
    
    <div class="panel-body">
      
      <ul class="list-group">
        @foreach($tasks as $task)
          <li class="list-group-item">
            <a href="{{ route('tasks.show', $task->id) }}"> {{ $task->name }} </a>
            @if(Auth::user()->id == $task->user_id)
                <a class="pull-right" href="{{ route('tasks.show', $task->id) }}"> Manage </a>
            @endif
          </li>
        @endforeach
      </ul>
    </div>
  </div>
  <div class="pull-right">{{ $tasks->links() }}</div>
</div>
@endsection

resources/views/tasks/show.blade.php
@extends('layouts.app')
@section('content')
       
    <div class="col-md-9 col-lg-9 col-sm-9 pull-left">

      <div class="well well-lg">
        <div class="container">
          <h1 class="display-3">{{ $task->name }}</h1>
          <p>Created by: <strong><a href="users/{{$task->user->id}}">{{ $task->user->name }}</a></strong></p>
          <p>Task for: <strong><a href="{{ route('projects.show', $task->project->id) }}">{{ $task->project->name }}</a> </strong></p>
          <p>Created at: <strong> {{ $task->created_at }} </strong></p>
          <p>Time frame: <strong> {{ $task->days }} days </strong></p>
        </div>
      </div>

      <div class="container">
        
        @include('partials.comments')

        <div class="row col-md-9 col-lg-9 col-sm-9 pull-left" style="
        background: white; margin-top: 20px; margin-bottom: 20px; border:solid 1px #e3e3e3; border-radius: 10px;">

          <div class="row container-fluid">
             <form method="post" action="{{ route('comments.store') }}">
              {{ csrf_field() }}

              <input type="hidden" name="commentable_type" value="App\task">
              <input type="hidden" name="commentable_id" value="{{ $task->id }}">
              <h2>Add a comment</h2>

              <div class="form-group @if($errors->has('url')) has-error @endif">
                <label for="comment-content">Work done (url/title)</label>
                <textarea placeholder="Enter url/title"
                        style="resize: vertical;" 
                        id="comment-content"
                        name="url"
                        rows="2" spellcheck="false" 
                        class="form-control autosize-target text-left"></textarea>
              </div>

              <div class="form-group @if($errors->has('body')) has-error @endif">
                <label for="comment-content">Comment</label>
                <textarea placeholder="Enter comment"
                        style="resize: vertical;" 
                        id="comment-content"
                        name="body"
                        rows="3" spellcheck="false" 
                        class="form-control autosize-target text-left"></textarea>
              </div>

              <div class="form-group">
                  <input type="submit" class="btn btn-primary" value="Submit"/>
              </div>

            </form>
          </div>
        </div>
      </div> <!-- /container -->
    </div>

    <div class="col-sm-3 col-md-3 col-lg-3 ">
      <div class="sidebar-module">

        <h4>Actions</h4>
        <ol class="list-unstyled">

        @if(Auth::user()->id == $task->user->id || auth()->user()->hasRole('admin'))
          <li><a href="{{ route('tasks.edit', $task->id) }}"><i class="fas fa-edit"></i> Edit</a></li>
        @endif

        <li><a href="{{ route('tasks.index') }}"><i class="fas fa-list-ul"></i> List of tasks</a></li>

        @if(Auth::user()->id == $task->user->id || auth()->user()->hasRole('admin'))
          <li>
            <a href=""
              onclick="var result = confirm('Are you sure you want to delete this task?');
                if (result) 
                {
                    event.preventDefault();
                    document.getElementById('delete-form').submit();
                }
            ">
              <i class="fas fa-trash-alt"></i> Delete
            </a>

            <form id="delete-form" action="{{ route('tasks.destroy',[$task->id]) }}"
              method="POST" style="display: none;">
                <input type="hidden" name="_method" value="delete">
                {{ csrf_field() }}
            </form>

          </li>
        @endif
        </ol>

        <hr/>
        @if(Auth::user()->id == $task->user->id)
          <h4>Add a member</h4>
          <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12">
              <form id="add-user" action="{{ route('tasks.adduser') }}" method="POST">
                {{ csrf_field() }}
                <div class="input-group">
                  <input class="form-control" name="task_id" value="{{ $task->id }}" type="hidden">
                  <input type="text" class="form-control" name="email" placeholder="Email">
                  <span class="input-group-btn">
                    <button class="btn btn-default" type="submit">Add!</button>
                  </span>
                </div><!-- /input-group -->
              </form>
            </div><!-- /.col-lg-6 -->
          </div><!-- /.row -->
          <hr/>
        @endif

        <h4>Members</h4>
        <ol class="list-unstyled">
          @foreach($task->users as $user)
            <li><a href="#"> {{ $user->email }} </a></li>
          @endforeach
        </ol>
      </div>          
    </div>
@endsection